# Generated by Django 2.0.9 on 2019-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0027_auto_20181114_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='_crystal_clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='enable_crystal_clear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exportformat',
            name='include_crystal_clear',
            field=models.BooleanField(default=True),
        ),
    ]
